// Auto-generated by stellar-contracts-kit
// Contract : CCK3W5FW2MY7IX7PZ65O7R6WYFLXRKDKT5MCIHVAHPIPRHZ223BPTU4N
// Network  : mainnet

export type ContractMethodFn<T, Args extends unknown[]> = {
  invoke: (...args: Args) => Promise<{ txHash: string }>
  read: () => Promise<{ result: T }>
}

export interface Contract {
  ping_alive: ContractMethodFn<void, []>
  get_deadline: ContractMethodFn<bigint, []>
  setup_switch: ContractMethodFn<void, [owner: string, beneficiary: string, token_id: string, timeout: bigint]>
  deposit_funds: ContractMethodFn<void, [amount: bigint]>
  claim_inheritance: ContractMethodFn<void, []>
  get_switch_status: ContractMethodFn<bigint, []>
  get_contract_balance: ContractMethodFn<bigint, []>
}

export const CONTRACT_ID = 'CCK3W5FW2MY7IX7PZ65O7R6WYFLXRKDKT5MCIHVAHPIPRHZ223BPTU4N' as const
